name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to latest version
      - uses: gautamkrishnar/blog-post-workflow@latest  # Ensure this is the latest stable version
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/itszed0"
